feat: popular page simplify(#354,#1089)
yujincheng08/BiliRoaming pull request #1141
Opened 2023-06-07 15:26 UTC by define9

热门页面净化
根据播放量,视频时长,标题,UP主过滤, 去除顶栏, 去除推荐关注

2023-06-07 15:30 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/Utils.kt
> +fun printFields(obj: Any?) {
debug 代码忘记删了？

2023-06-07 15:30 UTC, yujincheng08 commented on gradle.properties
> +android.injected.testOnly=false
这个不要加。

2023-06-07 15:51 UTC, define9 commented on gradle.properties
> +android.injected.testOnly=false
好的, 一会和上面那个一起去掉

2023-06-07 15:52 UTC, yujincheng08 commented on gradle.properties
> +android.injected.testOnly=false
还有几个注释掉的 debug 代码也记得去掉

2023-06-07 16:00 UTC, define9 commented
> 另外这个过滤感觉可以共用“首页推送过滤器”的规则，没必要再弄一个新的。相应把“首页推送过滤器” title 改成“推荐过滤器”，summary 改成“首页推荐和热门推荐过滤规则”

整合到一个Dialog里是叭? 好的

2023-06-07 16:01 UTC, yujincheng08 commented
> 整合到一个Dialog里是叭? 好的

![image](https://github.com/yujincheng08/BiliRoaming/assets/5022927/2927e8e3-0f29-4e3b-be5e-afc8ddcdb8ec)

2023-06-09 12:20 UTC, define9 commented
> > 整合到一个Dialog里是叭? 好的
> 
> ![image](https://github.com/yujincheng08/BiliRoaming/assets/5022927/2927e8e3-0f29-4e3b-be5e-afc8ddcdb8ec)
> 

晚上好呀哈哈，请问有空可以再看一下嘛

2023-06-09 13:46 UTC, define9 commented on app/src/main/java/me/iacn/biliroaming/hook/PopularHook.kt
> +class PopularHook(classLoader: ClassLoader) : BaseHook(classLoader) {
放到一起倒是可以, 因为我看具体过滤的方法, 比如过滤播放量, 具体的实现不太一样, 所以就把他们分开写了, 需要抽象一下嘛? 直接放到一个类会不会不太好,

2023-06-09 13:59 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PopularHook.kt
> +class PopularHook(classLoader: ClassLoader) : BaseHook(classLoader) {
具体过滤逻辑不一样可以放不同方法，但是成员变量是一样的，可以复用，所以放一个类也没问题吧？

2023-06-09 16:03 UTC, define9 commented on app/src/main/java/me/iacn/biliroaming/hook/PopularHook.kt
> +class PopularHook(classLoader: ClassLoader) : BaseHook(classLoader) {
> 具体过滤逻辑不一样可以放不同方法，但是成员变量是一样的，可以复用，所以放一个类也没问题吧？

🤤改成在PegasusHook里了

2023-06-11 14:54 UTC, david082321 requested changes

2023-06-11 14:54 UTC, david082321 commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="hide_suggest_follow_popular_summary">隱藏熱門的推薦關注（及其視頻）</string>
```suggestion
    <string name="hide_suggest_follow_popular_summary">隱藏熱門的推薦關注（及其影片）</string>
```

2023-06-11 14:54 UTC, david082321 commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="home_filter_title">首頁篩檢程式（推薦和熱門）</string>
```suggestion
    <string name="home_filter_title">首頁過濾器（推薦和熱門）</string>
```

2023-06-11 17:31 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +        private var POPULAR_DATA_VERSION = ""
不是常量不要用这种命名

2023-06-11 17:42 UTC, define9 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +        private var POPULAR_DATA_VERSION = ""
> 不是常量不要用这种命名

好的, 不好意思哈, 修改了

2023-06-11 17:53 UTC, yujincheng08 approved these changes

2023-06-11 18:02 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +                    val versionField = param.args[0].javaClass.getDeclaredField("lastParam_")
这里用 param.args[0].setField("lastParam_", xxx)

其他类似地方也全部这样改掉。

2023-06-11 18:02 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +            val hasContent = reasonText?.isNotEmpty() == true
isNotNullOrEmpty

2023-06-11 18:05 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +                else -> throw IllegalArgumentException("Invalid time format: $time")
b 站有什么改动这样抛异常会导致崩溃吧？给个 Long 的最大值好了。

2023-06-11 18:05 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +        instance.popularClass?.hookMethod(
用 XposedHelper 的东西

2023-06-11 18:06 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/PegasusHook.kt
> +            "index", "com.bapis.bilibili.app.show.popular.v1.PopularResultReq", object: XC_MethodHook(){
用 XposedHelper 接口。不需要直接用 XC_MethodHook

2023-06-11 18:12 UTC, merged

2023-06-11 18:16 UTC, yujincheng08 commented
不小心 merge 了，你再开一个 pr 吧

2023-06-13 03:51 UTC, define9 commented
> 不小心 merge 了，你再开一个 pr 吧

谢谢这段时间的细心指导啦