增加禁用长按评论区评论复制到剪切板Hook
yujincheng08/BiliRoaming pull request #268
Opened 2021-09-15 09:16 UTC by littleWhiteDuck

通过replaceMethod来达到不让评论复制剪切板的效果

2021-09-15 10:08 UTC, yujincheng08 requested changes

2021-09-15 10:08 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +    val commentCopyClass by Weak { "com.bilibili.app.comm.comment2.comments.a.t1\$s".findClassOrNull(mClassLoader) }
请不要直接写混淆名字

2021-09-15 10:08 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/CommentHook.kt
> +        instance.commentCopyClass?.replaceMethod( "a", Void::class.java){
同上

2021-09-15 14:08 UTC, littleWhiteDuck commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +    val commentCopyClass by Weak { "com.bilibili.app.comm.comment2.comments.a.t1\$s".findClassOrNull(mClassLoader) }
已经做了更改

2021-09-15 15:01 UTC, yujincheng08 requested changes
`应用程序/源文件/主要的/爪哇/我/商会/胆漫游` 是啥

2021-09-15 15:06 UTC, littleWhiteDuck commented
> `应用程序/源文件/主要的/爪哇/我/商会/胆漫游` 是啥

github用的少，点了谷歌翻译，可能导致了这个问题[狗头]

2021-09-15 15:58 UTC, yujincheng08 requested changes

2021-09-15 15:58 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/CommentHook.kt
> +        instance.commentCopyClass?.replaceMethod( "onLongClick", View::class.java){
格式化一下代码

2021-09-15 15:59 UTC, yujincheng08 commented
onLongClick 可以替换成微信那种自由复制不？

2021-09-15 16:06 UTC, littleWhiteDuck commented
我明天看看它的逻辑，试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月15日(周三) 晚上11:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yujincheng08/BiliRoaming] 增加禁用长按评论区评论复制到剪切板Hook (#268)




 
onLongClick 可以替换成微信那种自由复制不？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-09-16 09:51 UTC, littleWhiteDuck commented
> onLongClick 可以替换成微信那种自由复制不？

我试了一下，用了setTextIsSelectable，没有效果

2021-09-17 12:45 UTC, yujincheng08 approved these changes

2021-09-17 12:46 UTC, merged