Optimize area
yujincheng08/BiliRoaming pull request #402
Opened 2022-01-27 17:22 UTC by JasonKhew96

2022-01-27 19:32 UTC, yujincheng08 commented
1. 如何用 country 时候协程还没结束怎么办
2. 给搜索也过滤一下

2022-01-28 06:40 UTC, JasonKhew96 commented
> 1. 如何用 country 时候协程还没结束怎么办
> 2. 给搜索也过滤一下

1. 原来 `fetchJson` 没自动 `timeout` 呀，我自己加一个好了
2. 搜索已经过滤了，等一个~~真人~~测试

2022-01-28 06:40 UTC, yujincheng08 commented
不是 timeout 的问题，是同步问题，那边还没拿到结果这边就要用结果了就会 crash

2022-01-28 06:41 UTC, JasonKhew96 commented
> 不是 timeout 的问题，是同步问题，那边还没拿到结果这边就要用结果了就会 crash

怪了，我测试几次没 NPE，不懂 kotlin

2022-01-28 06:43 UTC, yujincheng08 commented
那不是 kt 或者什么的问题，那是概率问题。

2022-01-28 06:46 UTC, yujincheng08 commented
`country` 用 future 包一下，这样用的时候如果还没有结果就等待。如果超时或者错误返回个默认值。

2022-01-28 09:39 UTC, yujincheng08 requested changes

2022-01-28 09:39 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/XposedInit.kt
> +                        c
```suggestion
                            when (fetchJson(Constant.infoUrl)?.optJSONObject("data")
                                ?.optString("country")) {
                                "中国" -> "cn"
                                "香港", "澳门" -> "hk"
                                "台湾" -> "tw"
                                else -> "global"
                            }.also { Log.d("当前地区: $it") }
```

2022-01-28 09:39 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/SpeedTestDialog.kt
> +            ?.optString("base_url")?.replace("https", "http") ?: throw Throwable()
```suggestion
            ?.optString("base_url")?.replace("https", "http")
```

2022-01-28 09:39 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/SpeedTestDialog.kt
> +            } catch (t: Throwable) {
```suggestion
            val url = getTestUrl() ?: run {
```

2022-01-28 09:43 UTC, yujincheng08 requested changes

2022-01-28 09:43 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/SpeedTestDialog.kt
> +            if (XposedInit.country.get() == "cn") getPlayUrl(mainlandParams, arrayOf("hk", "tw"))
```suggestion
            if (XposedInit.country.get(5L, TimeUnit.SECONDS) == "cn") getPlayUrl(mainlandParams, arrayOf("hk", "tw"))
```

2022-01-28 09:43 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                if (XposedInit.country.get() == area.value.area) {
```suggestion
                if (XposedInit.country.get(5L, TimeUnit.SECONDS) == area.value.area) {
```

2022-01-28 09:43 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt
> +                it != XposedInit.country.get()
```suggestion
                runCatching { it != XposedInit.country.get(5L, TimeUnit.SECONDS) }.getOrNull() ?: true
```

2022-01-28 09:43 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/network/BiliRoamingApi.kt
> +                it != XposedInit.country.get()
其他也要 runCatching 一下以防超时

2022-01-28 10:09 UTC, JasonKhew96 commented
~~有什么事直接 改 吧，没空了，哎...~~

2022-01-28 11:23 UTC, yujincheng08 approved these changes

2022-01-28 11:23 UTC, merged