fix compatibility for old version
yujincheng08/BiliRoaming pull request #42
Opened 2020-11-15 00:55 UTC by rhjdvsgsgks

主要改了两个地方
1. 旧国际版没有 `MOBI_APP` 导致 platform 被识别成了标准版，加了条通过包名判断
2. 有些“去除更新”的修改版是通过在 `versionCode` 前加 9 实现的，加了几行判断前面有多少个 9 ，去掉前面的 9 再在最后加 0 ，从而实现获取到正确的版本号

剩下的就是对旧版中不存在的 class 使用 `findClassOrNull` 而不是 `findClass` 来减少对 xposed log 的刷屏

2020-11-15 12:28 UTC, yujincheng08 commented
还是不要兼容修改版的奇怪操作好。那种修改方式本来就有问题的。B站API是看版本返回格式的，这种修改版很容易以后API修改改出问题。

2020-11-15 12:30 UTC, yujincheng08 requested changes
No specialization for modified clients.

2020-11-15 19:08 UTC, rhjdvsgsgks commented
不是说特意去兼容修改版，这只是让模块获取到相对较为正确的版本号从而开启对应的功能，实际操作上还是对修改版进行了对官方版改进行的操作，并没有说为了修改版专门写了一些 hook 。至于“使用修改版导致官方 api 返回错误内容”就是用户的选择了，他选择了修改了版本号的版本就要承担这些，我是觉得模块应该既不帮他修改这些错误也不因此就阻止他使用部分功能（因为没获取到正确版本号导致部分功能不可用

2020-11-16 10:52 UTC, yujincheng08 commented
那他选择了修改了版本号的版本就要承担模块部分功能不兼容。这样是特意为了修改版弄了个codeversion的workaround并不好。

2020-11-16 11:02 UTC, closed without merging

2020-11-16 11:55 UTC, rhjdvsgsgks commented
已经改好了，是需要重发 pr 吗

2020-11-16 12:01 UTC, yujincheng08 commented
我已经帮你改好merge了