Throw away seperator and fix dynamic remove not completely
yujincheng08/BiliRoaming pull request #607
Opened 2022-05-15 12:39 UTC by zjns

- 抛弃分隔符，优化动态过滤器输入体验
- 并修复某些情况下根据内容关键字动态不能被移除的问题

2022-05-15 17:15 UTC, david082321 reviewed
dynamic_values 对应内容


    dyn_none = 0;          // 占位
    forward = 1;           // 转发
    av = 2;                // 稿件: ugc、小视频、短视频、UGC转PGC
    pgc = 3;               // pgc：番剧、PGC番剧、PGC电影、PGC电视剧、PGC国创、PGC纪录片
    courses = 4;           // 付费更新批次
    fold = 5;              // 折叠
    word = 6;              // 纯文字
    draw = 7;              // 图文
    article = 8;           // 专栏 原仅phone端
    music = 9;             // 音频 原仅phone端
    common_square = 10;    // 通用卡 方形
    common_vertical = 11;  // 通用卡 竖形
    live = 12;             // 直播卡 只有转发态
    medialist = 13;        // 播单 原仅phone端 只有转发态
    courses_season = 14;   // 付费更新批次 只有转发态
    ad = 15;               // 广告卡
    applet = 16;           // 小程序卡
    subscription = 17;     // 订阅卡
    live_rcmd = 18;        // 直播推荐卡
    banner = 19;           // 通栏
    ugc_season = 20;       // 合集卡
    subscription_new = 21; // 新订阅卡

2022-05-15 17:29 UTC, david082321 commented
怎么多了 reviewed 删不掉啊

2022-05-15 17:33 UTC, zjns commented
> dynamic_values 对应内容
> 
> ```
> dyn_none = 0;          // 占位
> forward = 1;           // 转发
> av = 2;                // 稿件: ugc、小视频、短视频、UGC转PGC
> pgc = 3;               // pgc：番剧、PGC番剧、PGC电影、PGC电视剧、PGC国创、PGC纪录片
> courses = 4;           // 付费更新批次
> fold = 5;              // 折叠
> word = 6;              // 纯文字
> draw = 7;              // 图文
> article = 8;           // 专栏 原仅phone端
> music = 9;             // 音频 原仅phone端
> common_square = 10;    // 通用卡 方形
> common_vertical = 11;  // 通用卡 竖形
> live = 12;             // 直播卡 只有转发态
> medialist = 13;        // 播单 原仅phone端 只有转发态
> courses_season = 14;   // 付费更新批次 只有转发态
> ad = 15;               // 广告卡
> applet = 16;           // 小程序卡
> subscription = 17;     // 订阅卡
> live_rcmd = 18;        // 直播推荐卡
> banner = 19;           // 通栏
> ugc_season = 20;       // 合集卡
> subscription_new = 21; // 新订阅卡
> ```

有一些不是很清楚，比如说fold、common_*、live、medialist、courses_season、subscription、banner、ugc_season、subscription_new。没见到过。明天看看能不能实际发出来相关类型的动态看看

2022-05-15 18:15 UTC, david082321 commented
拆包看了一下，还有这几个

    cour_up(24),
    topic_set(25),
    UNRECOGNIZED(-1)

2022-05-16 03:09 UTC, zjns commented
> 拆包看了一下，还有这几个
> 
> ```
> cour_up 24
> topic_set 25
> UNRECOGNIZED -1
> ```

结合 `com.bilibili.bplus.followinglist.model#j` 方法以及 `com.bapis.bilibili.app.dynamic.v2.DynamicType` 类补充了些类型，有些类型的名称完全是yy出来的 😂

2022-05-16 03:19 UTC, yujincheng08 requested changes

2022-05-16 03:19 UTC, yujincheng08 commented on app/src/main/res/values/arrays.xml
> +        <item>4,14</item>
尽量保持原子性

2022-05-16 03:38 UTC, zjns commented on app/src/main/res/values/arrays.xml
> +        <item>4,14</item>
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/10793522/168515813-1435342c-f947-41cf-8cfb-5df31fc830f4.png">

因为我看这两类在这个类里直接被归纳为一类，所以我也这样处理了，这个类里10和11也归为了一类，然后17和21都是订阅，我觉得没必要拆分

2022-05-16 03:40 UTC, yujincheng08 commented on app/src/main/res/values/arrays.xml
> +        <item>4,14</item>
但是 item 还是要保证原子性

2022-05-16 03:47 UTC, zjns commented on app/src/main/res/values/arrays.xml
> +        <item>4,14</item>
> 但是 item 还是要保证原子性

怎么做比较好哇.. 没想到好方法

2022-05-16 03:49 UTC, yujincheng08 commented on app/src/main/res/values/arrays.xml
> +        <item>4,14</item>
付费内容 1、2 这样就好。保持原子性可以让代码更容易维护。。。

2022-05-16 04:08 UTC, zjns commented on app/src/main/res/values/arrays.xml
> +        <item>4,14</item>
> 付费内容 1、2 这样就好。保持原子性可以让代码更容易维护。。。

确实，改了

2022-05-16 13:23 UTC, yujincheng08 approved these changes

2022-05-16 13:23 UTC, merged