Add TryWatchVipQualityHook
yujincheng08/BiliRoaming pull request #754
Opened 2022-08-20 16:15 UTC by KyuubiRan

2022-08-20 16:37 UTC, yujincheng08 requested changes

2022-08-20 16:37 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/TryWatchVipQualityHook.kt
> +}
文件末空行

2022-08-20 17:19 UTC, KyuubiRan commented on app/src/main/java/me/iacn/biliroaming/hook/TryWatchVipQualityHook.kt
> +}
西大师又开始 鸡蛋里挑骨头

2022-08-20 17:49 UTC, yujincheng08 requested changes
Conflict

2022-08-20 17:50 UTC, KyuubiRan commented
西大师应该 自己动手 刚刚没有冲突的 呜呜

2022-08-20 17:52 UTC, yujincheng08 approved these changes

2022-08-20 18:10 UTC, merged

2022-08-22 12:16 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/TryWatchVipQualityHook.kt
> +            instance.canTryWatchVipQuality().also { Log.d("TryWatchVipQualityHook method name: $it") },
这个 also 啥玩意儿

2022-08-22 12:18 UTC, KyuubiRan commented on app/src/main/java/me/iacn/biliroaming/hook/TryWatchVipQualityHook.kt
> +            instance.canTryWatchVipQuality().also { Log.d("TryWatchVipQualityHook method name: $it") },
落鸽忘记删了

2022-08-22 12:19 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/TryWatchVipQualityHook.kt
> +            instance.canTryWatchVipQuality().also { Log.d("TryWatchVipQualityHook method name: $it") },
PR

2022-08-22 12:28 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +            canTryWatchVipQuality = method m@{
这个 `m@` 又是啥

2022-08-22 12:29 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +            canTryWatchVipQuality = method m@{
完全没必要啊

2022-08-22 12:34 UTC, KyuubiRan commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +            canTryWatchVipQuality = method m@{
因为之前提示烂了

2022-08-22 12:42 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +            canTryWatchVipQuality = method m@{
PR

2022-08-22 13:00 UTC, KyuubiRan commented
https://github.com/yujincheng08/BiliRoaming/pull/760