Fix other area bangumi search
yujincheng08/BiliRoaming pull request #767
Opened 2022-08-26 23:33 UTC by zjns

Fix #766

2022-08-27 11:09 UTC, yujincheng08 commented
用 9a5996bd678ce9c9d9bfbc8c7ccf92a7093274ed 来解析和构造吧

2022-08-27 11:12 UTC, zjns commented
> 用 [9a5996b](https://github.com/yujincheng08/BiliRoaming/commit/9a5996bd678ce9c9d9bfbc8c7ccf92a7093274ed) 来解析和构造吧

可以

2022-08-27 11:17 UTC, yujincheng08 commented
记得参考 playurl 的 codestyle

2022-08-27 11:24 UTC, zjns commented
> 记得参考 playurl 的 codestyle

明白

2022-08-27 11:54 UTC, zjns commented
> 用 [9a5996b](https://github.com/yujincheng08/BiliRoaming/commit/9a5996bd678ce9c9d9bfbc8c7ccf92a7093274ed) 来解析和构造吧

你这个proto跟6.87.0版本的差别有点大，对不上，比如ReasonStyle，APP里的没有那么多字段，我可能要改proto

2022-08-27 12:12 UTC, yujincheng08 commented
我就是 6.87 扒出来的呀

2022-08-27 12:16 UTC, zjns commented
> 我就是 6.87 扒出来的呀

<img width="841" alt="image" src="https://user-images.githubusercontent.com/10793522/187029816-c373d4fd-8cec-4226-bde2-074f9781eede.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/10793522/187029852-f83c6912-df7b-46f8-af03-cc375f43bf00.png">

明显不对啊，没这么多字段，序号也对不上

2022-08-27 12:16 UTC, yujincheng08 commented
草，我看了另一个 ReasonStyle。。

2022-08-27 12:17 UTC, zjns commented
> 草，我看了另一个 ReasonStyle。。

好吧，我改了就是了

2022-08-27 16:44 UTC, zjns commented
@yujincheng08 改好了

2022-08-27 18:16 UTC, yujincheng08 approved these changes

2022-08-27 18:28 UTC, yujincheng08 requested changes

2022-08-27 18:28 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                param.args[1] = Proxy.newProxyInstance(
这里可以直接调用 `retrieveAreaSearchV3` 然后直接 `handler.onNext(); handler.onComplete(); param.result = null`？似乎没必要请求一下 b 站。

2022-08-27 18:28 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                val request = SearchByTypeRequest.parseFrom(
可以先反射拿 type，如果 type 不在 AREA_TYPES 里面可以直接 `return`，毕竟反序列化一次比较慢。

2022-08-27 18:28 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                        m.invoke(handler, *args)
用语法糖 m(handler, *args)

2022-08-27 18:36 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                val request = SearchByTypeRequest.parseFrom(
这里我都不想反序列化，直接拿Nav类生成实例插进去，这样应该更快，毕竟这里只需要修改nav数据，没必要反复倒腾，而且如果以后all数据夹杂非av类型的item，还要补proto。

2022-08-27 18:44 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                val request = SearchByTypeRequest.parseFrom(
@yujincheng08 你觉得怎么样，这里只用反射

2022-08-27 20:04 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                val request = SearchByTypeRequest.parseFrom(
这个可以。只序列化和反序列化 nav 就行。

2022-08-28 02:47 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/hook/BangumiSeasonHook.kt
> +                val request = SearchByTypeRequest.parseFrom(
> 可以先反射拿 type，如果 type 不在 AREA_TYPES 里面可以直接 `return`，毕竟反序列化一次比较慢。

这里是在拿到数据时立即hook的，这几个类型一定不会有，所以不用判断type是否存在。

2022-08-28 02:50 UTC, zjns commented
@yujincheng08 改好了

2022-08-28 02:56 UTC, yujincheng08 approved these changes

2022-08-28 02:58 UTC, merged