Add auto generate chs subtitle feature
yujincheng08/BiliRoaming pull request #790
Opened 2022-09-05 18:34 UTC by zjns

2022-09-06 04:53 UTC, yujincheng08 commented
感觉这种实现不太好。我记得字幕有个对应的类，能不能直接构造那个类呢？

大概这样：
1. 获取字幕列表，中间加入一个简体版本，url 依然用繁体版本，但是加入一些标识
2. 反序列化后，判断标识，然后进行转换

这样就不用 hook 请求了。毕竟请求是热点函数，很影响性能。

2022-09-06 05:03 UTC, zjns commented
> 感觉这种实现不太好。我记得字幕有个对应的类，能不能直接构造那个类呢？
> 
> 大概这样：
> 
> 1. 获取字幕列表，中间加入一个简体版本，url 依然用繁体版本，但是加入一些标识
> 2. 反序列化后，判断标识，然后进行转换
> 
> 这样就不用 hook 请求了。毕竟请求是热点函数，很影响性能。

虽然比较影响性能，但这样无疑能处理更多关于请求的hook，比如说有些bson响应格式解析的，B站混淆的很严重，根本无从下手，这种方式就能轻松处理。至于你说的方式要研究下了。

2022-09-06 08:19 UTC, zjns commented
大致看了下，那几个字幕解析实体`SubtitleModel`、`SubtitleItemModel`是没有用的，或者说早期版本是在用的，现在都是请求拿到响应转为字符串或字节数组，最后处理为字节数组扔给chronos native解析。所以还是要拦截请求的某一环节才行。在找有没有相对不那么热点的hook点。

2022-09-06 09:02 UTC, yujincheng08 commented
哦我想起来了，现在都是 native 了，导致自定义字幕也用不了了

具体代码我再周末 CR 一下

2022-09-07 04:16 UTC, zjns commented
@yujincheng08 麻烦评估下，换了一个hook点，现在是hook `FileFormatParser` 这个 `Retrofit` 响应转换器，这个 parser 我调试看了下只有字幕下载在用，影响最小，我觉得没啥问题。

2022-09-07 06:12 UTC, yujincheng08 requested changes

2022-09-07 06:12 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
```kotlin
        URL("https://i0.hdslb.com/bfs/new_dyn/48cfbdfb5f40b3de2b19511b16cfcbb7169021.png").openStream().use {
            val bitmap = BitmapFactory.decodeStream(it)
            val buffer = ByteBuffer.allocate(bitmap.byteCount)
            bitmap.copyPixelsToBuffer(buffer)
            bitmap.recycle()
            GZIPInputStream(buffer.array().inputStream()).use { i ->
                FileOutputStream(File(currentContext.filesDir, "t2cn.txt").absolutePath).use { o ->
                    i.copyTo(o)
                }
            }
        }
```

2022-09-07 06:12 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/BasicDictionary.kt
> +    val dict: Trie<String>,
逐字替换没必要用字典树了？

2022-09-07 06:22 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/GenerateSubtitleHook.kt
> +                subtitleParser = param.args[0]
能用 proxy 吗

2022-09-07 06:25 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                name = "retrofit2.Response".from(classloader)?.name
减少一次dex find难到不更快吗？本来有些类大部分时候就没混淆

2022-09-07 06:25 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                name = "retrofit2.Response".from(classloader)?.name
> 减少一次dex find难道不更快吗？本来有些类大部分时候就没混淆

2022-09-07 06:28 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/BasicDictionary.kt
> +    val dict: Trie<String>,
> 逐字替换没必要用字典树了？

这里涉及到最佳匹配，不是简单的逐字替换，比如说有转换规则：
```
亁=乾
乾隆=乾隆
乾一杯=干一杯
```
当匹配到时乾一杯，应该用干一杯。

2022-09-07 06:44 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
> 

1. 就是因为`Bitmap`拿不到png图片的原始数据，才自己写了个 `Decoder`。
2. 把数据塞到png里面要做填充，达到相应规格该有的像素数据量，所以这里png实际上会有数据块尾部0填充，要记录真实数据长度，然后只读这一段。

2022-09-07 06:51 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                    this@hookInfo.okHttp.responseBody.class_.from(classloader) ?: return@okIO
这里因为要用到 ResponseBody 里面的三个成员，所以就抽出来了，我觉得是没问题的，至于是否应该放在 `okhttp` 下面，可以讨论。

2022-09-07 06:52 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                val responseClass = "okhttp3.Response".from(classloader)
理由同上。

2022-09-07 07:38 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                name = "retrofit2.Response".from(classloader)?.name
之前是混淆了的

2022-09-07 08:00 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                name = "retrofit2.Response".from(classloader)?.name
那要这个操作了，我觉得可以先试着找一次，没找到再用 dexHelper。

2022-09-07 08:41 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
我还以为你是这样生成图片的：
```kotlin
    val data = ByteArray(4 * 4 * 4)
    val bmp = Bitmap.createBitmap(4, 4, Bitmap.Config.ARGB_8888)
    val buffer = ByteBuffer.wrap(data)
    bmp.copyPixelsFromBuffer(buffer)
    bmp.compress(Bitmap.CompressFormat.PNG, 100, FileOutputStream(File(currentContext.filesDir, "t2cn.png")))
```
这样生成图片有问题吗？传上去再下下来可以还原出数据吗？

2022-09-07 12:52 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
decode之后拿不到原始像素数据，就很奇怪，拿到的字节数组大小是一样的，但是内容不一样，除了前面附加的的长度是一样的，后面字节全部不一样。
<img width="967" alt="image" src="https://user-images.githubusercontent.com/10793522/188882204-5fed5e42-9196-48ea-8853-736b6c34a255.png">
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/10793522/188882857-074062a2-0df4-4024-a5e5-9a8f454a4a2e.png">

[t2cn.txt](https://github.com/yujincheng08/BiliRoaming/files/9506325/t2cn.txt)

2022-09-07 13:00 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/hook/GenerateSubtitleHook.kt
> +                subtitleParser = param.args[0]
改了。

2022-09-07 15:09 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
我明天看看

2022-09-08 09:23 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
PR 代码里的图片是用 Python 脚本 Pillow 库编码的
<img width="551" alt="image" src="https://user-images.githubusercontent.com/10793522/189085453-bfcb5d50-7b22-4d49-8d4a-59851ba41731.png">

2022-09-09 01:29 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
感觉是因为 `isPremultiplied`

2022-09-09 01:36 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
不要 alpha 通道了，用 RGB_565 来存，一个像素 2B

2022-09-09 01:51 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
都不行

2022-09-09 02:05 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
一点突破，noAlpha 创建出来的 bitmap 解出来没问题，noAlpha 后 A 全变成了黑色，对应 java 字节 -1，感觉就是 alpha 通道的锅。
<img width="794" alt="image" src="https://user-images.githubusercontent.com/10793522/189256977-2122608f-4b5c-461d-b91f-aea82fbadc36.png">

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/10793522/189256956-1df42fde-3f53-420e-a906-99fb4da4a02a.png">

2022-09-09 02:15 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
实在不行的话编码的时候每3个字节插入一个-1，解码后把-1去掉就行。

2022-09-09 02:23 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
```kotlin
        MainScope().launch(Dispatchers.IO) {
            val src = Bitmap.createBitmap(16, 16, Bitmap.Config.RGB_565)
            val bytes = Random.nextBytes(16 * 16 * 2)
            Log.e("BiliRoaming", bytes.contentToString())
            src.copyPixelsFromBuffer(ByteBuffer.wrap(bytes))
            val o = ByteArrayOutputStream()
            src.compress(Bitmap.CompressFormat.PNG, 100, o)
            val target = BitmapFactory.decodeByteArray(o.toByteArray(), 0, o.size(), BitmapFactory.Options().apply {
                inPreferredConfig = Bitmap.Config.RGB_565
            })
            ByteBuffer.allocate(16 * 16 * 2).apply {
                target.copyPixelsToBuffer(this)
                Log.e("BiliRoaming", array().contentToString())
            }
        }
```

2022-09-09 02:25 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
刚才试的时候忘了改 inPreferredConfig 了，再试试

2022-09-09 02:28 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
可以啦
<img width="1632" alt="image" src="https://user-images.githubusercontent.com/10793522/189259622-0848f2a5-897c-4020-87c2-28dde82709ec.png">

2022-09-09 02:28 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
传到 B 站看看。png 理论是不会被压缩的

2022-09-09 02:41 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
没问题
<img width="640" alt="image" src="https://user-images.githubusercontent.com/10793522/189261113-699bb260-cc99-4522-8e5c-4675e70a0b88.png">

2022-09-09 02:41 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +            val decoded = URL(dictUrl).openStream().buffered()
ok。那你基于这个实现一下。

2022-09-09 03:18 UTC, zjns commented
改好了

2022-09-09 03:20 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
没必要二次压缩。png 本来就有压缩了。

2022-09-09 03:24 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
> 没必要二次压缩。png 本来就有压缩了。

有必要，压缩之后小几十KB

2022-09-09 03:28 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
不压缩150+KB，压缩之后91KB。

2022-09-09 03:28 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
不用。小几十 K 是因为 png 的压缩 deflate 没 gzip 好而已。实际上 gzip 之后 png 再压就压不了了。但是 http 打开压缩之后本来就能压缩传输了，所以不需要压缩这么多次。

2022-09-09 03:29 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
> 不用。小几十 K 是因为 png 的压缩 deflate 没 gzip 好而已。实际上 gzip 之后 png 再压就压不了了。但是 http 打开压缩之后本来就能压缩传输了，所以不需要压缩这么多次。

好吧，那我改下。

2022-09-09 03:31 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
记得用 getContent，里面打开了压缩。

2022-09-09 03:43 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
但B站的图片下载貌似不支持gzip传输呀
<img width="1752" alt="image" src="https://user-images.githubusercontent.com/10793522/189267298-9f97bbc4-6109-44f1-9902-7b784b94c6d1.png">

2022-09-09 03:44 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
没看到 content-encoding header

2022-09-09 04:59 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                    this@hookInfo.okHttp.responseBody.class_.from(classloader) ?: return@okIO
是说不能直接用 `responseBodyClass` 吗

2022-09-09 05:02 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                    this@hookInfo.okHttp.responseBody.class_.from(classloader) ?: return@okIO
> 是说不能直接用 `responseBodyClass` 吗

我是指现在用到了 `ResponseBody` 的三个成员，就抽了一个 `ResponseBody` `message` 出来。
<img width="289" alt="image" src="https://user-images.githubusercontent.com/10793522/189275319-a497874f-c4ad-4a99-ab32-0caba71c1172.png">

2022-09-09 05:04 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                    this@hookInfo.okHttp.responseBody.class_.from(classloader) ?: return@okIO
这有什么关系？我的意思是这个 class 已经 load 过了为什么现在再 load 一次

2022-09-09 05:10 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/BiliBiliPackage.kt
> +                    this@hookInfo.okHttp.responseBody.class_.from(classloader) ?: return@okIO
明白了，刚开始没懂你的意思，这里是因为抽出来之后把原来引用的地方全都按之前的方式无脑改了下，没考虑到这一点，我改下。

2022-09-09 05:13 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/GenerateSubtitleHook.kt
> +        "com.bapis.bilibili.community.service.dm.v1.DMMoss".from(mClassLoader)
把 `BangumiPlayUrlHook` 的那个合并过来，Hook 改名为 `SubtitleHook` 吧

2022-09-09 05:17 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/hook/GenerateSubtitleHook.kt
> +        "com.bapis.bilibili.community.service.dm.v1.DMMoss".from(mClassLoader)
OK

2022-09-09 05:17 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
那试试 lossless webp？

2022-09-09 05:18 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
还要试吗，我不想试了，好麻烦

2022-09-09 05:22 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
我试了一下，encode decode 是没问题的，就是不知道上传之后怎样

2022-09-09 05:23 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
好好好，我再试下

2022-09-09 05:27 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +    val dictExist: Boolean get() = File(dictFilePath).isFile
明明每次用 `dictFilePath` 都包一个 `File` 那为什么还要 `.absolutePath`

2022-09-09 05:31 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +    val dictExist: Boolean get() = File(dictFilePath).isFile
哈好好，我改

2022-09-09 05:37 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/DictionaryContainer.kt
> +        private val sInstance by lazy { DictionaryContainer() }
kotlin 单例用 `object DictionaryContainer`

2022-09-09 05:40 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/DictionaryFactory.kt
> +    private fun String.liteSplit(delimiter: Char): Array<String> {
`split` 有个可选参数 `limit` 能实现一样的功能

2022-09-09 05:43 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/DictionaryFactory.kt
> +    private fun String.liteSplit(delimiter: Char): Array<String> {
> `split` 有个可选参数 `limit` 能实现一样的功能

这里主要是考虑到 kotlin 的 split 不够高效，才自己写了个轻量化的 split。

2022-09-09 05:44 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/DictionaryContainer.kt
> +    fun getDictionary(key: String): BasicDictionary {
这是还能支持多个字典？有必要吗？

2022-09-09 05:46 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/zhconverter/dictionary/DictionaryFactory.kt
> +    private fun String.liteSplit(delimiter: Char): Array<String> {
![image](https://user-images.githubusercontent.com/5022927/189279918-0e3ff8e7-1389-4900-8d96-c50661c6e010.png)
不用 reg delimiter 似乎也是 indexof

2022-09-09 06:39 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/hook/GenerateSubtitleHook.kt
> +        "com.bapis.bilibili.community.service.dm.v1.DMMoss".from(mClassLoader)
> 把 `BangumiPlayUrlHook` 的那个合并过来，Hook 改名为 `SubtitleHook` 吧

原来已经有个 SubtitleHook 了，自定义字幕样式

2022-09-09 06:40 UTC, yujincheng08 commented on app/src/main/java/me/iacn/biliroaming/hook/GenerateSubtitleHook.kt
> +        "com.bapis.bilibili.community.service.dm.v1.DMMoss".from(mClassLoader)
那就加到那里吧

2022-09-09 10:50 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
> 我试了一下，encode decode 是没问题的，就是不知道上传之后怎样

`WEBP_LOSSLESS` 好像最低 Android R 才支持？

2022-09-09 11:04 UTC, zjns commented on app/src/main/java/me/iacn/biliroaming/utils/SubtitleHelper.kt
> +                GZIPInputStream(bytes.inputStream()).use { it.copyTo(o) }
> 我试了一下，encode decode 是没问题的，就是不知道上传之后怎样

同样 `100 quality`，`RGB_565` 生成的图片文件大小（197KB）相比 png（170KB）更大，还是用 png 吧。

2022-09-10 00:46 UTC, zjns commented
@yujincheng08 该改的都改了，代码也进行了缩减优化，麻烦看下还有什么问题不。

2022-09-10 04:19 UTC, yujincheng08 approved these changes

2022-09-10 04:19 UTC, merged