custom playback speed
yujincheng08/BiliRoaming pull request #98
Opened 2021-02-15 17:47 UTC by rhjdvsgsgks

先不要关 #92 ，还有一小点问题，比如弹幕速度不会随默认播放速度改变，需要手动切换一次播放速度  
单独开一个 ijkhook 的文件是因为找不到合适的地方，且要写的东西还挺多随便塞到别的文件里感觉不是很好。日后还有一些东西要放到这里，比如 #92 的“阻止弹幕速度随播放速度变化”和 #93 的设置默认清晰度

2021-02-15 17:54 UTC, yujincheng08 commented
我觉得你可以换个思路，试试我之前的思路，弹幕速度什么的都没问题（没记错的话）：
找到播放器那几个速度 (1.0, 2.0, 0.5) 的 `view `，设置它们的 `longClickListener` 为打开一个 `dialog` 选择速度，对话框的 `positiveButton` 是调用这个 `view` 的 `onClick` 这样就行了。

2021-02-15 17:58 UTC, yujincheng08 commented
```kotlin
        var pp = false

        "com.bilibili.playerbizcommon.widget.function.setting.u".findClass(mClassLoader)?.hookAfterAllConstructors { param ->
            val x = param.thisObject.getObjectFieldAs<ViewGroup>("c")
            (x.getChildAt(0) as TextView).run {
                text = "0.1"
                setOnLongClickListener {
                    (it as TextView).text = "0.2"
                    it.callOnClick()
                    true
                }
            }

            x.addView(TextView(x.context).run {
                val o = x.getChildAt(0) as TextView
                textSize = o.textSize
                setTextColor(o.textColors)
                setPadding(o.paddingLeft, o.paddingTop, o.paddingRight, o.paddingBottom)
                text = "0.1"
                contentDescription = "bbplayer_playersetting_speed"
                layoutParams = o.layoutParams
                id = 1919810
                this
            })
            if (!pp) {
                param.thisObject.javaClass.setStaticObjectField("m", floatArrayOf(0.5f, 0.75f, 1.0f, 1.25f, 1.5f, 2.0f, 0.1f))
                param.thisObject.javaClass.getStaticObjectFieldAs<FloatArray>("m")[0] = 0.1f
                param.thisObject.javaClass.setStaticObjectField("n", param.thisObject.javaClass.getStaticObjectFieldAs<IntArray>("n").toMutableList().run {
                    add(1919810)
                    toIntArray()
                })
                pp = true
            }
        }

```

2021-02-15 18:21 UTC, rhjdvsgsgks commented
感谢思路，我是直接 hook 了初始化播放器时传入速度参数的地方，如果要设成 hook view 的 longClickListener 的话因为新版用的 ijkplayerv2 而老版用的是 ijkplayer ，可能需要两套逻辑来 hook 相关的 view ，而且使用两个设置入口降低了鲁棒性，如果功能是可以正常使用的却因为因为无法打开功能的设置而无法使用就太尴尬了，所以我选择把数值的设置放在了主设置里  
关于弹幕速度不正确是因为我只修改了播放器的传入播放速度，弹幕的还没有改，打算回头和“阻止弹幕速度随播放速度变化”一起发上来，因为这两个功能几乎是一回事

2021-02-16 13:38 UTC, yujincheng08 commented
~所以我从来不兼容旧版~

2021-02-16 13:52 UTC, rhjdvsgsgks commented
主要是因为我自己还在用旧版所以才保留了一点对旧版的兼容性，新版实在太臃肿了🤣

还有这是等我修好了再 merge 的意思吗？还是说先合了再等我过几天来修？

2021-02-16 14:00 UTC, yujincheng08 commented
对
~然后现在 conflict 了~

2021-02-19 15:53 UTC, rhjdvsgsgks commented
差不多都写好了，现在有个问题，我本来是想在开启“阻止弹幕速度随播放速度变化”后在设置面板设置弹幕速度时也使用绝对的弹幕速度而非根据播放速度进行计算的结果，但我发现弹幕速度滑杆的精度极低，只有四个档位，最高是 1.6 最低是 0.45 ，实际弹幕速度是由 `弹幕速度 x ( 2 - 播放速度 )` 得到的，当计算结果大于等于 2 时使结果为 2 ，计算结果小于等于 0.3 时使结果为 0.3 ，通过这种方法巧妙的实现了比较高的精度（而非只有固定几个档位），所以我在想要不加个“精确修改现有弹幕速度”的功能，虽然有 root 的话直接去改下 preference 就行，但毕竟不是每个人都有 root

2021-02-21 16:50 UTC, rhjdvsgsgks commented
都修好了

2021-02-21 18:07 UTC, yujincheng08 requested changes
代码风格统一一下吧，比如大小写还有空格tab什么的

2021-02-22 13:31 UTC, rhjdvsgsgks commented
改好了

2021-02-22 13:33 UTC, yujincheng08 commented
你那个 player core 有问题，你看我 music hook 的实现：
https://github.com/yujincheng08/BiliRoaming/blob/0365809e69f298b1d96271cd13bd872c221c6318/app/src/main/java/me/iacn/biliroaming/hook/MusicNotificationHook.kt#L132

2021-02-22 13:59 UTC, merged

2021-03-14 08:27 UTC, BoBppy commented
在6.18-6.20这些版本中 播放器中的倍速列表并没有随设置而改变(即不生效) 
但默认播放速度设置为自定义列表中的值是可用的:smile:

2021-03-14 09:40 UTC, rhjdvsgsgks commented
收到，过几天修

2021-03-14 09:43 UTC, rhjdvsgsgks commented
是这样的，关于列表的显示在每个版本中的位置有较大的差别所以就没改，是个 feature 不是 bug

2021-03-14 09:51 UTC, BoBppy commented
😅啊这